In [1]:
import pandas as pd
import sys
from pathlib import Path
project_root = Path().resolve().parent
sys.path.append(str(project_root))

In [2]:
results = pd.read_csv(
    "../artifacts/metrics/experiment_results.csv"
)

results

,timestamp,model,sampling,precision,recall,f1_score,roc_auc,pr_auc,threshold,training_time_sec,cv_precision_mean,cv_recall_mean,cv_f1_mean,cv_roc_auc_mean,cv_pr_auc_mean,cv_precision_std,cv_recall_std,cv_f1_std,cv_roc_auc_std,cv_pr_auc_std
0,2026-05-24T20:40:14.512559,logistic_regression,none,0.027347,0.918367,0.053113,0.972083,0.718971,0.3,0.4547,0.062795,0.913762,0.117468,0.982484,0.757136,0.003615,0.023045,0.006178,0.010168,0.052096
1,2026-05-24T20:42:02.147477,random_forest,none,0.922222,0.846939,0.882979,0.952909,0.855418,0.3,26.6434,0.955499,0.738591,0.832452,0.952895,0.839402,0.024561,0.024640,0.007103,0.012971,0.022107
2,2026-05-24T20:42:10.641926,xgboost,none,0.615942,0.867347,0.720339,0.979844,0.862696,0.3,0.7080,0.828419,0.829990,0.826745,0.981679,0.837992,0.049664,0.050882,0.021146,0.009790,0.018661
3,2026-05-24T20:42:13.257908,logistic_regression,undersampling,0.022581,0.928571,0.044089,0.976126,0.656263,0.3,0.0472,0.036865,0.916326,0.070820,0.981810,0.662264,0.005089,0.027111,0.009362,0.010126,0.048495
4,2026-05-24T20:42:16.328403,random_forest,undersampling,0.014536,0.948980,0.028633,0.977781,0.695625,0.3,0.1170,0.051321,0.911263,0.096974,0.978945,0.738056,0.008659,0.033821,0.015282,0.006664,0.029332
5,2026-05-24T20:42:19.469224,xgboost,undersampling,0.010852,0.948980,0.021458,0.984372,0.633193,0.3,0.1647,0.015276,0.949367,0.030058,0.980106,0.726439,0.001758,0.034896,0.003393,0.011421,0.036528
6,2026-05-24T20:42:24.941785,logistic_regression,oversampling,0.027397,0.918367,0.053207,0.972004,0.720353,0.3,0.9065,0.062929,0.916293,0.117728,0.982594,0.756566,0.003413,0.023339,0.005825,0.010036,0.051802
7,2026-05-24T20:45:07.640910,random_forest,oversampling,0.881720,0.836735,0.858639,0.962822,0.856082,0.3,35.5963,0.936811,0.763973,0.840587,0.952506,0.834993,0.031364,0.032503,0.014182,0.014760,0.019454
8,2026-05-24T20:45:19.965685,xgboost,oversampling,0.110682,0.877551,0.196571,0.983344,0.798784,0.3,1.6477,0.235428,0.829958,0.364353,0.968231,0.778414,0.036143,0.045671,0.040051,0.008734,0.025661
9,2026-05-24T20:45:26.475133,logistic_regression,smote,0.027565,0.918367,0.053524,0.970843,0.724469,0.3,1.1269,0.058126,0.918825,0.109306,0.980545,0.752751,0.003095,0.021942,0.005401,0.011451,0.048325
10,2026-05-24T20:52:12.394692,random_forest,smote,0.701613,0.887755,0.783784,0.968443,0.872437,0.3,89.8845,0.889741,0.796981,0.839100,0.974321,0.844836,0.033734,0.045162,0.015780,0.018994,0.025742
11,2026-05-24T20:52:29.751526,xgboost,smote,0.033522,0.908163,0.064657,0.979655,0.793321,0.3,2.3000,0.063326,0.880785,0.118034,0.972799,0.782973,0.005347,0.045561,0.008995,0.011650,0.027663

In [3]:
results.sort_values(
    by="pr_auc",
    ascending=False
)

,timestamp,model,sampling,precision,recall,f1_score,roc_auc,pr_auc,threshold,training_time_sec,cv_precision_mean,cv_recall_mean,cv_f1_mean,cv_roc_auc_mean,cv_pr_auc_mean,cv_precision_std,cv_recall_std,cv_f1_std,cv_roc_auc_std,cv_pr_auc_std
10,2026-05-24T20:52:12.394692,random_forest,smote,0.701613,0.887755,0.783784,0.968443,0.872437,0.3,89.8845,0.889741,0.796981,0.839100,0.974321,0.844836,0.033734,0.045162,0.015780,0.018994,0.025742
2,2026-05-24T20:42:10.641926,xgboost,none,0.615942,0.867347,0.720339,0.979844,0.862696,0.3,0.7080,0.828419,0.829990,0.826745,0.981679,0.837992,0.049664,0.050882,0.021146,0.009790,0.018661
7,2026-05-24T20:45:07.640910,random_forest,oversampling,0.881720,0.836735,0.858639,0.962822,0.856082,0.3,35.5963,0.936811,0.763973,0.840587,0.952506,0.834993,0.031364,0.032503,0.014182,0.014760,0.019454
1,2026-05-24T20:42:02.147477,random_forest,none,0.922222,0.846939,0.882979,0.952909,0.855418,0.3,26.6434,0.955499,0.738591,0.832452,0.952895,0.839402,0.024561,0.024640,0.007103,0.012971,0.022107
8,2026-05-24T20:45:19.965685,xgboost,oversampling,0.110682,0.877551,0.196571,0.983344,0.798784,0.3,1.6477,0.235428,0.829958,0.364353,0.968231,0.778414,0.036143,0.045671,0.040051,0.008734,0.025661
11,2026-05-24T20:52:29.751526,xgboost,smote,0.033522,0.908163,0.064657,0.979655,0.793321,0.3,2.3000,0.063326,0.880785,0.118034,0.972799,0.782973,0.005347,0.045561,0.008995,0.011650,0.027663
9,2026-05-24T20:45:26.475133,logistic_regression,smote,0.027565,0.918367,0.053524,0.970843,0.724469,0.3,1.1269,0.058126,0.918825,0.109306,0.980545,0.752751,0.003095,0.021942,0.005401,0.011451,0.048325
6,2026-05-24T20:42:24.941785,logistic_regression,oversampling,0.027397,0.918367,0.053207,0.972004,0.720353,0.3,0.9065,0.062929,0.916293,0.117728,0.982594,0.756566,0.003413,0.023339,0.005825,0.010036,0.051802
0,2026-05-24T20:40:14.512559,logistic_regression,none,0.027347,0.918367,0.053113,0.972083,0.718971,0.3,0.4547,0.062795,0.913762,0.117468,0.982484,0.757136,0.003615,0.023045,0.006178,0.010168,0.052096
4,2026-05-24T20:42:16.328403,random_forest,undersampling,0.014536,0.948980,0.028633,0.977781,0.695625,0.3,0.1170,0.051321,0.911263,0.096974,0.978945,0.738056,0.008659,0.033821,0.015282,0.006664,0.029332
3,2026-05-24T20:42:13.257908,logistic_regression,undersampling,0.022581,0.928571,0.044089,0.976126,0.656263,0.3,0.0472,0.036865,0.916326,0.070820,0.981810,0.662264,0.005089,0.027111,0.009362,0.010126,0.048495
5,2026-05-24T20:42:19.469224,xgboost,undersampling,0.010852,0.948980,0.021458,0.984372,0.633193,0.3,0.1647,0.015276,0.949367,0.030058,0.980106,0.726439,0.001758,0.034896,0.003393,0.011421,0.036528

In [4]:
from src.data.load_data import load_dataset

df = load_dataset()

fraud_df = df[df["Class"] == 1]
legitimate_df = df[df["Class"] == 0]
print(fraud_df)
print(legitimate_df)

            Time        V1        V2        V3        V4        V5        V6  \
541        406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623        472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920      4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108      6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329      7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V21       V22       V23  \
541    -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211
623     0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966
4920    0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726
6108   -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207
6329    1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173

             V24       V25       V26       V27       V28  Amount  Class
541     0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1
623    -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1
4920   -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1
6108   -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1
6329   -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1
...          ...       ...       ...       ...       ...     ...    ...
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1

[492 rows x 31 columns]
            Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193
...          ...        ...        ...       ...       ...       ...
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278
...          ...       ...       ...       ...  ...       ...       ...
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99
...          ...       ...       ...       ...       ...       ...     ...
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00

        Class
0           0
1           0
2           0
3           0
4           0
...       ...
284802      0
284803      0
284804      0
284805      0
284806      0

[284315 rows x 31 columns]

In [6]:
fraud_sample_1 = (
    fraud_df
    .iloc[0]
    .drop("Class")
    .to_dict()
)

fraud_sample_2 = (
    fraud_df
    .iloc[1]
    .drop("Class")
    .to_dict()
)

legitimate_sample_1 = (
    legitimate_df
    .iloc[0]
    .drop("Class")
    .to_dict()
)

legitimate_sample_2 = (
    legitimate_df
    .iloc[1]
    .drop("Class")
    .to_dict()
)

In [7]:
def convert_to_python_types(sample):

    return {

        key: float(value)

        for key, value in sample.items()
    }


fraud_sample_1 = (
    convert_to_python_types(
        fraud_sample_1
    )
)

fraud_sample_2 = (
    convert_to_python_types(
        fraud_sample_2
    )
)

legitimate_sample_1 = (
    convert_to_python_types(
        legitimate_sample_1
    )
)

legitimate_sample_2 = (
    convert_to_python_types(
        legitimate_sample_2
    )
)

In [ ]:
import json
import requests

batch_payload = {

    "transactions": [

        fraud_sample_1,

        fraud_sample_2,

        legitimate_sample_1,

        legitimate_sample_2
    ]
}


# =========================================
# Pretty Print Payload
# =========================================

print(
    json.dumps(
        batch_payload,
        indent=2
    )
)

{
  "transactions": [
    {
      "Time": 406.0,
      "V1": -2.3122265423263,
      "V2": 1.95199201064158,
      "V3": -1.60985073229769,
      "V4": 3.9979055875468,
      "V5": -0.522187864667764,
      "V6": -1.42654531920595,
      "V7": -2.53738730624579,
      "V8": 1.39165724829804,
      "V9": -2.77008927719433,
      "V10": -2.77227214465915,
      "V11": 3.20203320709635,
      "V12": -2.89990738849473,
      "V13": -0.595221881324605,
      "V14": -4.28925378244217,
      "V15": 0.389724120274487,
      "V16": -1.14074717980657,
      "V17": -2.83005567450437,
      "V18": -0.0168224681808257,
      "V19": 0.416955705037907,
      "V20": 0.126910559061474,
      "V21": 0.517232370861764,
      "V22": -0.0350493686052974,
      "V23": -0.465211076182388,
      "V24": 0.320198198514526,
      "V25": 0.0445191674731724,
      "V26": 0.177839798284401,
      "V27": 0.261145002567677,
      "V28": -0.143275874698919,
      "Amount": 0.0
    },
    {
      "Time": 472.0,
      "V1": -3.0435406239976,
      "V2": -3.15730712090228,
      "V3": 1.08846277997285,
      "V4": 2.2886436183814,
      "V5": 1.35980512966107,
      "V6": -1.06482252298131,
      "V7": 0.325574266158614,
      "V8": -0.0677936531906277,
      "V9": -0.270952836226548,
      "V10": -0.838586564582682,
      "V11": -0.414575448285725,
      "V12": -0.503140859566824,
      "V13": 0.676501544635863,
      "V14": -1.69202893305906,
      "V15": 2.00063483909015,
      "V16": 0.666779695901966,
      "V17": 0.599717413841732,
      "V18": 1.72532100745514,
      "V19": 0.283344830149495,
      "V20": 2.10233879259444,
      "V21": 0.661695924845707,
      "V22": 0.435477208966341,
      "V23": 1.37596574254306,
      "V24": -0.293803152734021,
      "V25": 0.279798031841214,
      "V26": -0.145361714815161,
      "V27": -0.252773122530705,
      "V28": 0.0357642251788156,
      "Amount": 529.0
    },
    {
      "Time": 0.0,
      "V1": -1.3598071336738,
      "V2": -0.0727811733098497,
      "V3": 2.53634673796914,
      "V4": 1.37815522427443,
      "V5": -0.338320769942518,
      "V6": 0.462387777762292,
      "V7": 0.239598554061257,
      "V8": 0.0986979012610507,
      "V9": 0.363786969611213,
      "V10": 0.0907941719789316,
      "V11": -0.551599533260813,
      "V12": -0.617800855762348,
      "V13": -0.991389847235408,
      "V14": -0.311169353699879,
      "V15": 1.46817697209427,
      "V16": -0.470400525259478,
      "V17": 0.207971241929242,
      "V18": 0.0257905801985591,
      "V19": 0.403992960255733,
      "V20": 0.251412098239705,
      "V21": -0.018306777944153,
      "V22": 0.277837575558899,
      "V23": -0.110473910188767,
      "V24": 0.0669280749146731,
      "V25": 0.128539358273528,
      "V26": -0.189114843888824,
      "V27": 0.133558376740387,
      "V28": -0.0210530534538215,
      "Amount": 149.62
    },
    {
      "Time": 0.0,
      "V1": 1.19185711131486,
      "V2": 0.26615071205963,
      "V3": 0.16648011335321,
      "V4": 0.448154078460911,
      "V5": 0.0600176492822243,
      "V6": -0.0823608088155687,
      "V7": -0.0788029833323113,
      "V8": 0.0851016549148104,
      "V9": -0.255425128109186,
      "V10": -0.166974414004614,
      "V11": 1.61272666105479,
      "V12": 1.06523531137287,
      "V13": 0.48909501589608,
      "V14": -0.143772296441519,
      "V15": 0.635558093258208,
      "V16": 0.463917041022171,
      "V17": -0.114804663102346,
      "V18": -0.183361270123994,
      "V19": -0.145783041325259,
      "V20": -0.0690831352230203,
      "V21": -0.225775248033138,
      "V22": -0.638671952771851,
      "V23": 0.101288021253234,
      "V24": -0.339846475529127,
      "V25": 0.167170404418143,
      "V26": 0.125894532368176,
      "V27": -0.0089830991432281,
      "V28": 0.0147241691924927,
      "Amount": 2.69
    }
  ]
}